apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: demo
  labels:
    app: app1
spec:
  selector:
    app.kubernetes.io/name: app1
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: demo
  labels:
    app: app2
spec:
  selector:
    app.kubernetes.io/name: app2
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
