apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
    app.kubernetes.io/name: demo
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  strategy: {}
  template:
    metadata:
      labels:
        app: demo
        app.kubernetes.io/name: demo
    spec:
      containers:
      - image: demo:local
        imagePullPolicy: Never
        name: demo
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8181
            name: metrics
            protocol: TCP
        env:
          - name: PROFILE
            value: local
          - name: DEMO_DOWNSTREAM_ADDRESS
            value: "http://app1.demo.svc.cluster.local:8080"
        resources: {}
