apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: demo
  labels:
    app: app1
spec:
  selector:
    app.kubernetes.io/name: app1
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 8181
      targetPort: 8181
      name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: demo
  labels:
    app: app2
spec:
  selector:
    app.kubernetes.io/name: app2
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 8181
      targetPort: 8181
      name: metrics
